project:
  type: book
  output-dir: docs

book:
  title: "Teste Não-paramétrico de Kappa"
  author: "Mário Diego"
  date: "22/04/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

